# Task 12: canary release, 1 replica (~10% of traffic)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-canary
  labels:
    owner: mayank
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp-canary
      track: canary
  template:
    metadata:
      labels:
        app: myapp-canary
        track: canary
    spec:
      containers:
        - name: web
          image: hashicorp/http-echo:1.0
          args: ["-listen=:5678", "-text=CANARY v2"]
          ports:
            - containerPort: 5678
