# No PV written by hand: the "standard" StorageClass provisions one on demand
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dynamic-pvc
  labels: {owner: mayank}
spec:
  storageClassName: standard
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 200Mi
