# A PersistentVolume created by hand (static provisioning), backed by a node directory
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mayank-pv
  labels: {owner: mayank}
spec:
  capacity:
    storage: 1Gi
  accessModes: ["ReadWriteOnce"]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /tmp/mayank-pv-data
    type: DirectoryOrCreate
