apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tickethub
  namespace: argocd
  finalizers: ["resources-finalizer.argocd.argoproj.io"]
spec:
  project: default
  source:
    repoURL: https://github.com/mayank-0789/Devops-Assignment-1.git
    targetRevision: main
    path: final-devops-project/helm/tickethub
    helm:
      valueFiles: [values-gitops.yaml]
  destination:
    server: https://kubernetes.default.svc
    namespace: tickethub
  syncPolicy:
    automated: {prune: true, selfHeal: true}
    syncOptions: [CreateNamespace=true]
