apiVersion: v1
kind: Pod
metadata:
  name: dns-test-client
  labels:
    owner: mayank
    role: client
spec:
  containers:
    - name: client
      image: curlimages/curl:8.10.1
      command: ["sleep", "infinity"]
