{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  labels: {{- include "tickethub.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend: {service: {name: {{ .Release.Name }}-backend, port: {number: {{ .Values.backend.port }}}}}
          - path: /docs
            pathType: Prefix
            backend: {service: {name: {{ .Release.Name }}-backend, port: {number: {{ .Values.backend.port }}}}}
          - path: /openapi.json
            pathType: Exact
            backend: {service: {name: {{ .Release.Name }}-backend, port: {number: {{ .Values.backend.port }}}}}
          - path: /
            pathType: Prefix
            backend: {service: {name: {{ .Release.Name }}-frontend, port: {number: 80}}}
{{- end }}
