apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-postgres-data
  labels: {{- include "tickethub.labels" . | nindent 4 }}
spec:
  accessModes: ["ReadWriteOnce"]
  {{- if .Values.postgres.storageClassName }}
  storageClassName: {{ .Values.postgres.storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.postgres.storage }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-postgres
  labels: {{- include "tickethub.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  replicas: 1
  strategy: {type: Recreate}   # one writer on one volume
  selector:
    matchLabels: {app.kubernetes.io/instance: {{ .Release.Name }}, app.kubernetes.io/component: database}
  template:
    metadata:
      labels: {app.kubernetes.io/instance: {{ .Release.Name }}, app.kubernetes.io/component: database, owner: mayank}
    spec:
      containers:
        - name: postgres
          image: {{ .Values.postgres.image }}
          ports: [{containerPort: 5432, name: pg}]
          envFrom:
            - configMapRef: {name: {{ .Release.Name }}-config}
            - secretRef: {name: {{ .Release.Name }}-db-secret}
          env:
            - {name: PGDATA, value: /var/lib/postgresql/data/pgdata}
          volumeMounts: [{name: data, mountPath: /var/lib/postgresql/data}]
          readinessProbe:
            exec: {command: ["pg_isready", "-U", "{{ .Values.postgres.user }}", "-d", "{{ .Values.postgres.database }}"]}
            periodSeconds: 5
          livenessProbe:
            exec: {command: ["pg_isready", "-U", "{{ .Values.postgres.user }}", "-d", "{{ .Values.postgres.database }}"]}
            periodSeconds: 15
          resources: {{- toYaml .Values.postgres.resources | nindent 12 }}
      volumes:
        - name: data
          persistentVolumeClaim: {claimName: {{ .Release.Name }}-postgres-data}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-postgres
  labels: {{- include "tickethub.labels" . | nindent 4 }}
spec:
  selector: {app.kubernetes.io/instance: {{ .Release.Name }}, app.kubernetes.io/component: database}
  ports: [{port: 5432, targetPort: pg}]
