apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-secret
  labels: {{- include "tickethub.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.postgres.password | quote }}
